[package]
name = "binary"
version = "0.1.0"
edition = "2021"

[lib]
name = "binary"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
submod2.workspace = true
